# Generated by Django 3.1.7 on 2021-03-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolestest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
