# Generated by Django 3.1.7 on 2021-03-12 09:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rolestest', '0003_cartitem_item_menu_order_purchaseditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 9, 56, 49, 448398, tzinfo=utc)),
        ),
    ]
