# Generated by Django 3.1.7 on 2021-03-12 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rolestest', '0004_auto_20210312_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 10, 27, 53, 478776, tzinfo=utc)),
        ),
    ]
