# Generated by Django 3.1.7 on 2021-03-19 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rolestest', '0009_auto_20210319_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Excellent')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 19, 15, 42, 797705, tzinfo=utc)),
        ),
    ]
