# Generated by Django 3.1.7 on 2021-03-28 16:07

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc
import rolestest.models


class Migration(migrations.Migration):

    dependencies = [
        ('rolestest', '0010_auto_20210320_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 16, 7, 35, 457929, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(rolestest.models.get_deleted_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
