# Generated by Django 3.1.7 on 2021-03-28 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rolestest', '0011_auto_20210328_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 17, 6, 58, 649557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='item',
            field=models.CharField(max_length=25),
        ),
    ]
