# Generated by Django 3.1.7 on 2021-03-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolestest', '0013_auto_20210329_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=80),
        ),
    ]
